-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 16:14:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel_reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_reservas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `hotel_reservas` ;

-- -----------------------------------------------------
-- Table `hotel_reservas`.`Estados_Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Estados_Reserva` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `hotel_reservas`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `hotel_reservas`.`Tipos_Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Tipos_Habitacion` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio_base` DECIMAL(10,2) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`id_tipo`));


-- -----------------------------------------------------
-- Table `hotel_reservas`.`Habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Habitaciones` (
  `id_habitacion` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NOT NULL,
  `id_tipo_habitacion` INT NOT NULL,
  `estado` ENUM('disponible', 'mantenimiento', 'ocupada') NULL DEFAULT 'disponible',
  PRIMARY KEY (`id_habitacion`),
  UNIQUE INDEX `numero` (`numero` ASC) VISIBLE,
  INDEX `id_tipo_habitacion` (`id_tipo_habitacion` ASC) VISIBLE,
  CONSTRAINT `FK_id_tipo_Tipos_Habitacion`
    FOREIGN KEY (`id_tipo_habitacion`)
    REFERENCES `hotel_reservas`.`Tipos_Habitacion` (`id_tipo`));


-- -----------------------------------------------------
-- Table `hotel_reservas`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_habitacion` INT NOT NULL,
  `id_estado` INT NOT NULL DEFAULT 1,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_reserva`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_habitacion` (`id_habitacion` ASC) VISIBLE,
  INDEX `id_estado` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `FK_id_cliente_Clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `hotel_reservas`.`Clientes` (`id_cliente`),
  CONSTRAINT `FK_id_habitacion_Habitaciones`
    FOREIGN KEY (`id_habitacion`)
    REFERENCES `hotel_reservas`.`Habitaciones` (`id_habitacion`),
  CONSTRAINT `FK_id_estado_Estados_Reserva`
    FOREIGN KEY (`id_estado`)
    REFERENCES `hotel_reservas`.`Estados_Reserva` (`id_estado`));


-- -----------------------------------------------------
-- Table `hotel_reservas`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_reservas`.`Pagos` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `id_reserva` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `FK_id_reserva_reservas`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `hotel_reservas`.`Reservas` (`id_reserva`));

CREATE USER 'HotelUser' IDENTIFIED BY 'HotelManagment+2026';

GRANT ALL ON `mydb`.* TO 'HotelUser';
GRANT ALL ON `hotel_reservas`.* TO 'HotelUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
